--- #YAML:1.0
name:                Email-Simple-Creator
version:             1.420
abstract:            Email::Simple constructor for starting anew.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Email::Date:                   
    Email::Simple:                 
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Casey West <casey@geeknest.com>
