--- #YAML:1.0
name:                Email-Simple-Creator
version:             1.424
abstract:            Email::Simple constructor for starting anew.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Email::Date::Format:           1.000
    Email::Simple:                 2.003
    Test::More:                    0.47
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Ricardo SIGNES <rjbs@cpan.org>
